packages:
  - apps/*
  - packages/*
catalog:
  "@eslint/js": ^9.8.0
  "@testing-library/jest-dom": ^6.4.8
  "@testing-library/react": ^16.0.0
  "@types/node": ^22.2.0
  "@types/react": ^18.3.3
  "@types/react-dom": ^18.3.0
  "@vitejs/plugin-react-swc": ^3.5.0
  eslint: ^9.8.0
  eslint-plugin-react-hooks: ^5.1.0-rc.0
  eslint-plugin-react-refresh: ^0.4.9
  globals: ^15.9.0
  jsdom: ^24.1.1
  memfs: ^4.11.1
  react: ^18.3.1
  react-dom: ^18.3.1
  typescript: ^5.5.3
  typescript-eslint: ^8.0.0
  vite: ^5.4.0
  vite-plugin-static-copy: ^1.0.6
  vitest: ^2.0.5
